name: Build Bluefin LTS HWE

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    with:
      image-name: bluefin-hwe
      image-desc: "Bluefin LTS, built on CentOS Stream with bootc"
      flavor: hwe
